/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AbrirChamadoRouteImport } from './routes/abrir-chamado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProdutividadeRouteImport } from './routes/dashboard.produtividade'
import { Route as DashboardOrdensRouteImport } from './routes/dashboard.ordens'
import { Route as DashboardDocumentosRouteImport } from './routes/dashboard.documentos'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirChamadoRoute = AbrirChamadoRouteImport.update({
  id: '/abrir-chamado',
  path: '/abrir-chamado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutividadeRoute = DashboardProdutividadeRouteImport.update({
  id: '/produtividade',
  path: '/produtividade',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdensRoute = DashboardOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentosRoute = DashboardDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir-chamado': typeof AbrirChamadoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/documentos': typeof DashboardDocumentosRoute
  '/dashboard/ordens': typeof DashboardOrdensRoute
  '/dashboard/produtividade': typeof DashboardProdutividadeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir-chamado': typeof AbrirChamadoRoute
  '/login': typeof LoginRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/documentos': typeof DashboardDocumentosRoute
  '/dashboard/ordens': typeof DashboardOrdensRoute
  '/dashboard/produtividade': typeof DashboardProdutividadeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir-chamado': typeof AbrirChamadoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/documentos': typeof DashboardDocumentosRoute
  '/dashboard/ordens': typeof DashboardOrdensRoute
  '/dashboard/produtividade': typeof DashboardProdutividadeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir-chamado'
    | '/dashboard'
    | '/login'
    | '/dashboard/clientes'
    | '/dashboard/documentos'
    | '/dashboard/ordens'
    | '/dashboard/produtividade'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir-chamado'
    | '/login'
    | '/dashboard/clientes'
    | '/dashboard/documentos'
    | '/dashboard/ordens'
    | '/dashboard/produtividade'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/abrir-chamado'
    | '/dashboard'
    | '/login'
    | '/dashboard/clientes'
    | '/dashboard/documentos'
    | '/dashboard/ordens'
    | '/dashboard/produtividade'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirChamadoRoute: typeof AbrirChamadoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir-chamado': {
      id: '/abrir-chamado'
      path: '/abrir-chamado'
      fullPath: '/abrir-chamado'
      preLoaderRoute: typeof AbrirChamadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtividade': {
      id: '/dashboard/produtividade'
      path: '/produtividade'
      fullPath: '/dashboard/produtividade'
      preLoaderRoute: typeof DashboardProdutividadeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ordens': {
      id: '/dashboard/ordens'
      path: '/ordens'
      fullPath: '/dashboard/ordens'
      preLoaderRoute: typeof DashboardOrdensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documentos': {
      id: '/dashboard/documentos'
      path: '/documentos'
      fullPath: '/dashboard/documentos'
      preLoaderRoute: typeof DashboardDocumentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardDocumentosRoute: typeof DashboardDocumentosRoute
  DashboardOrdensRoute: typeof DashboardOrdensRoute
  DashboardProdutividadeRoute: typeof DashboardProdutividadeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardDocumentosRoute: DashboardDocumentosRoute,
  DashboardOrdensRoute: DashboardOrdensRoute,
  DashboardProdutividadeRoute: DashboardProdutividadeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirChamadoRoute: AbrirChamadoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
